- name: Install HaProxy
  ansible.builtin.apt:
    name: haproxy
    state: latest

- name: Copy haproxy.conf to /etc/haproxy/haproxy.cnf
  ansible.builtin.template:
    src: haproxy.cnf.j2
    dest: /etc/haproxy/haproxy.cnf
  notify: restart haproxy

- name: Ensure that HaProxy is started und enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true


