- name: Download InfluxDB deb package
  ansible.builtin.get_url:
    url: "{{ influxdb_deb_url }}"
    dest: "{{ influxdb_deb_local }}"
    mode: '0644'

- name: Install InfluxDB
  ansible.builtin.apt:
    deb: "{{ influxdb_deb_local }}"
    state: present

- name: Enable and start InfluxDB service
  ansible.builtin.systemd:
    name: influxdb
    enabled: yes
    state: started
