- name: Download InfluxDB deb package
  ansible.builtin.get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /tmp/influxdb_1.8.10_amd64.deb
    mode: '0644'

- name: Install InfluxDB
  ansible.builtin.apt:
    deb: /tmp/influxdb_1.8.10_amd64.deb
    # state: present

- name: Copy infuxdb conf to  /etc/influxdb/influxdb.conf
  ansible.builtin.template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: restart influxdb

- name: Enable and start InfluxDB service
  ansible.builtin.systemd:
    name: influxdb
    enabled: yes
    state: started

- name: Download telegraf deb  package
  ansible.builtin.get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb
    dest: /tmp/telegraf_1.28.2-1_amd64.deb
    mode: 0644

- name: Install Telegraf
  ansible.builtin.apt:
    deb: /tmp/telegraf_1.28.2-1_amd64.deb

- name: Copy Telegraf conf to /etc/telegraf
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf

- name: Create /home/backup/influxdb directory owned by user backup
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: 0750

- name: Copy crontab file to /etc/cron.d/influxdb-backup
  ansible.builtin.template:
    src: influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup
  

