- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart influxdb exporter
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: restarted