- name: Create keyrings dir for grafana
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download GPG keys
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: grafana

- name: install Grafana
  ansible.builtin.apt:
    name: grafana
      #state: present

- name: Ensure that grafana is started and enabled
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true

- name: Copy grafana.ini 
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: restart grafana
  
- name: Copy Datasources config to /etc/grafana
  ansible.builtin.template:
    src: datasources.yaml.j2
    dest: /etc/grafana/provisioning/datasources/main.yaml
  notify: restart grafana

- name: Copy Dashboards config to /etc/grafana
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/main.yaml
  notify: restart grafana

- name: Create directory /var/lib/grafana/dashboards
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: Copy dashboards
  ansible.builtin.copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/main.json
  notify: restart grafana
   
- name: Set Home dashboard
  ansible.builtin.copy:
    src: main.json
    dest: /usr/share/grafana/public/dashboards/home.json 
  notify: restart grafana 
