- name: install uWSGI
  ansible.builtin.apt:
    name: uwsgi

- name: install uWSGI plugin
  ansible.builtin.apt:
    name: uwsgi-plugin-python3

- name: uWSGI configuration for AGAMA
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true
  notify: restart uwsgi

- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true


