---  
- name: Initial setup
  hosts: all
  roles:
    - init
  tags: init

- name: DNS Server
  hosts: dns_servers
  roles:
    - bind
    - bind_exporter
  tags: bind

- name: Resolv.conf
  hosts: resolvers
  roles:
    - resolvers


- name: Database server
  hosts: db_servers
  roles:
    - mysql
    - mysql_exporter
  tags:
    - mysql
    - mx


- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
      #- nginx
      #- nginx_exporter
  tags: 
    - web
    - mx

- name: Nginx
  hosts: all
  roles:
    - nginx
      #- nginx_exporter
  tags: nginx

- name: Prometheus 
  hosts: prometheus
  roles:
    - prometheus
  tags: prom

- name: grafana
  hosts: grafana
  roles:
    - docker
    - grafana
  tags: graf

- name: influxdb
  hosts: influxdb
  roles:
    - influxdb
  tags: influ 

- name: pinger
  hosts: pinger
  roles:
    - pinger
  tags: ping  

#- name: backup
 # hosts: all
 # roles:
 #   - backup
 # tags: back
