---  
- name: Initial setup
  hosts: all
  roles:
    - init
  tags: init

- name: DNS Server
  hosts: dns_servers
  roles:
    - bind
    - bind_exporter
  tags: bind

- name: Resolv.conf
  hosts: resolvers
  roles:
    - resolvers


- name: Database server
  hosts: db_servers
  roles:
    - mysql
    - mysql_exporter
  tags: mysql


- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
    - nginx_exporter
  tags: web

- name: Prometheus 
  hosts: prometheus
  roles:
    - prometheus
  tags: prom
