- name: Create directory /opt/agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: DDownolad Hudolejev Agama app files
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/opt/agama/{{ item.dest }}"
  loop:
    - { url: 'https://raw.githubusercontent.com/hudolejev/agama/master/agama.py', dest: 'agama.py' }
    - {url: 'https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile', dest: 'Dockerfile' }

- name: Build Agama docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Install und start Agama from container
  community.docker.docker_container:
    name: agama-{{ item }}
    image: agama
    published_ports: "{{ agama_base_port + item }}:8000"
    env:
      AGAMA_DATABASE_URI=mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}
  loop: "{{ range(1, agama_container_count + 1) | list }}"
  no_log: true
