- name: Install MySQL exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter

- name: Copy my.cnf to /var/lib/prometheus
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: root
    mode: 0640
  notify: restart mysql exporter
  # no_log: true

- name: Create MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
      # no_log: true

- name: Copy collect slave status file to /etc/default/prometheus-mysqld-exporter
  ansible.builtin.copy:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify: restart mysql exporter 

