- name: Install MySql server
  ansible.builtin.apt:
    name: mysql-server

      #- name: Install python3-pymysql
      #ansible.builtin.apt:
      #name: python3-pymysql

- name: copy override.cnf to mysql conf
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
    mode: 0644
  notify: restart mysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add MySql user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "{{ mysql_database }}.*:ALL"

- name: Ensure that MySql server is started and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
 


