- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: restart nginx_exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: restarted


