- name: Install Prometheus Bind exporter
  ansible.builtin.apt:
   name: prometheus-bind-exporter

- name: Ensure bind exported is started and enabled
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: started
    enabled: true 
