- name: Download and unarchive keepalived-exporter
  ansible.builtin.unarchive:
    src: http://backup/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
      # creates: /usr/local/bin/keepalived-exporter

- name: copy keepalived exporter
  ansible.builtin.copy:
    src: /usr/local/bin/keepalived-exporter-1.2.0.linux-amd64/keepalived-exporter
    dest: /usr/local/bin/keepalived-exporter
    remote_src: yes
    mode: 0755

- name: Copy keepalived-exporter.service file to /etc/systemd
  ansible.builtin.template:
    src: keepalived-exporter.service.j2
    dest: /etc/systemd/system/keepalived-exporter.service
  notify: daemon reload

- name: ensure that Keepalived exporter is running und enabled
  ansible.builtin.service:
    name: keepalived-exporter
    state: started
    enabled: true 
 

