- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus


- name: Copy Prometheus conf to /etc/prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: restart prometheus

- name: copy ARGS to /etc/default/prometheus
  ansible.builtin.template:
    src: prometheus
    dest: /etc/default/prometheus
  notify: restart prometheus
