- name: Install Prometheus Nginx Exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Ensure that nginx exporter is starte und enabled
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true

      #- name: copy nginx conf
      #ansible.builtin.template:
      #src: exporter.j2
      #dest: /etc/nginx/sites-enabled/exporter
      #notify: restart nginx exporter

      
