- name: stop resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: Copy resolv.conf file
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf 

