- name: Get variables
  ansible.builtin.setup:

- name: See what variables collected
  ansible.builtin.debug:
    msg: "{% for vm in groups['all'] %} nameserver {{ hostvars[vm]['ansible_default_ipv4']['address'] }}{% endfor %}"
      # var: hostvars['kagu22-2']['ansible_facts']['default_ipv4']['address']  
      
- name: Install Bind9
  ansible.builtin.apt:
    name: bind9

- name: Verify that bind is started and enabled
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true

- name: Copy named.conf.options to /etc/bind
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9
  no_log: true

- name: Copy named.conf.local to /etc/bind
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9 

- name: Copy Zone file
  ansible.builtin.template:
    src: zone.j2
    dest: /var/cache/bind/db.{{ domain_name }}
    force: no
  notify: reload rndc
  when: inventory_hostname in groups['dns_masters'] 

- name: Copy reversed Zone file
  ansible.builtin.template:
    src: zone.reversed.j2
    dest: /var/cache/bind/db.{{ domain }}.reversed
  notify: reload rndc 
