# - name: Ansible ping module
#   ansible.builtin.ping:

#- name: add user juri
#  ansible.builtin.user:
#    name: juri

#- name: add user roman
#  ansible.builtin.user:
#    name: roman

#- name: add user Juri keys
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: add user Roman keys
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install Prometheus Node Exporters
  ansible.builtin.apt:
    name: prometheus-node-exporter
