# - name: Ansible ping module
#   ansible.builtin.ping:

#- name: add user juri
#  ansible.builtin.user:
#    name: juri

#- name: add user roman
#  ansible.builtin.user:
#    name: roman

#- name: add user Juri keys
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: add user Roman keys
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install Prometheus Node Exporters
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Install present  ca-certificates=20230311
  ansible.builtin.apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    state: present

- name: Install Rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: latest

- name: Copy telegraf.conf to /etc/rsyslog.d/
  ansible.builtin.template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: restart rsyslog

- name: Ensure that Rsyslog is started und enabled
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Create user Backup
  ansible.builtin.user:
    name: backup
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa

- name: Add backup server SSH key to the list of known hosts
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: 0644 

- name: Create /home/backup/restore directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: 0750

- name: Install Duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present

